model_name_or_path: "pankajmathur/orca_mini_v3_7b"
dataset: "HydraLM/corpus_1_clustered_formatted"
use_auth: true
# output_dir: "./output_v2/7b_cluster030"
#run_name: "partitioned_v3_standardized_030"
format: "input-output"
logging_steps: 10
source_max_len: 2048
target_max_len: 2048
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 0.0002
save_strategy: "steps"
data_seed: 42
num_train_epochs: 2
eval_steps: 200
save_steps: 200
save_total_limit: 10
evaluation_strategy: "steps"
eval_dataset_size: 1024
max_eval_samples: 1000
per_device_eval_batch_size: 2
do_train: true
do_eval: true
do_mmlu_eval: true
metric_for_best_model: eval_loss
load_best_model_at_end: true
greater_is_better: false
dataloader_num_workers: 8
group_by_length: false
logging_strategy: "steps"
remove_unused_columns: false
lora_r: 64
lora_alpha: 16
lora_modules: "all"
double_quant: true
quant_type: "nf4"
bf16: true
bits: 4
warmup_ratio: 0.03
lr_scheduler_type: "constant"
gradient_checkpointing: true
adam_beta2: 0.999
max_grad_norm: 0.3
lora_dropout: 0.1
weight_decay: 0.0
seed: 0
push_to_hub: true
hub_strategy: "all_checkpoints"
hub_model_id: "HydraLM"
report_to: wandb