model_name_or_path: "NousResearch/Nous-Hermes-llama-2-7b"
use_auth: true
output_dir: "./output"
logging_steps: 10
save_strategy: "steps"
data_seed: 42
save_steps: 500
save_total_limit: 40
evaluation_strategy: "steps"
eval_dataset_size: 1024
max_eval_samples: 1000
per_device_eval_batch_size: 1
max_new_tokens: 320
dataloader_num_workers: 1
group_by_length: true
logging_strategy: "steps"
remove_unused_columns: false
do_train: true
do_eval: true
do_mmlu_eval: true
lora_r: 64
lora_alpha: 16
lora_modules: "all"
double_quant: true
quant_type: "nf4"
bits: 4
warmup_ratio: 0.03
lr_scheduler_type: "constant"
gradient_checkpointing: true
dataset: "oasst1"
source_max_len: 16
target_max_len: 512
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
max_steps: 1875
eval_steps: 187
learning_rate: 0.0002
adam_beta2: 0.999
max_grad_norm: 0.3
lora_dropout: 0.1
weight_decay: 0.0
seed: 0
max_memory: 40000
